### ISSUE TITLE
Undefined name: all_train used before it is defined

### ISSUE THREAD

**Issue by cclauss** [THUDM/cogdl#11]
https://github.com/THUDM/cogdl/blob/master/cogdl/tasks/node_classification_sample.py#L106

**Comment by qibinc** [comment]
Hi @cclauss ,

Thank you very much for reporting this to us. We're working on testing the code comprehensively. Will fix in the future.

**Comment by cenyk1230** [comment]
Hi @cclauss,

We are planning to rebuild our whole code and the code (node_classification_sample.py) is temporarily deleted and will be rewritten in the future. Thank you for your support and understanding.
