### ISSUE TITLE
when I run the example of combaining model,dataset and task in the tutorial, the pycharm return "Using backend: pytorch" and there is nothing about the ret. 

### ISSUE THREAD

**Issue by GorgeousWang** [THUDM/cogdl#130]
when I run the example of combaining model,dataset and task in the tutorial, the pycharm return "Using backend: pytorch" and there is nothing about the ret. 

Error:
Using backend: pytorch

**Comment by cenyk1230** [comment]
@GorgeousWang Please give more details, e.g., which example, error screenshot.

**Comment by GorgeousWang** [comment]
> @GorgeousWang Please give more details, e.g., which example, error screenshot.

from cogdl.tasks import build_task
from cogdl.datasets import build_dataset
from cogdl.models import build_model
from cogdl.utils import build_args_from_dict

def deepwalk_ppi():

    default_dict = {'hidden_size': 64, 'num_shuffle': 1, 'cpu': True}
    args = build_args_from_dict(default_dict)

    # model, dataset and task parameters
    args.model = 'spectral'
    args.dataset = 'ppi'
    args.task = 'community_detection'

    # build model, dataset and task
    dataset = build_dataset(args)
    model = build_model(args)
    task = build_task(args)

    # train model and get evaluate results
    ret = task.train()
    print(ret)

if __name__ == '__main__':
    deepwalk_ppi()



python console:
D:\Anaconda3\envs\pytorch\python.exe D:/codespace/pyspace/autocogdl/turial/combine.py
Using backend: pytorch
Traceback (most recent call last):
  File "D:/codespace/pyspace/autocogdl/turial/combine.py", line 27, in <module>
    deepwalk_ppi()
  File "D:/codespace/pyspace/autocogdl/turial/combine.py", line 20, in deepwalk_ppi
    task = build_task(args)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\cogdl\tasks\__init__.py", line 49, in build_task
    return TASK_REGISTRY[args.task](args)
KeyError: 'community_detection'

Process finished with exit code 1

**Comment by cenyk1230** [comment]
@GorgeousWang The tutorial is talking about how to create a **new** task in the cogdl. You can run examples in the `examples` directory of our repo.

**Comment by GorgeousWang** [comment]
> @GorgeousWang The tutorial is talking about how to create a **new** task in the cogdl. You can run examples in the `examples` directory of our repo.

**Comment by GorgeousWang** [comment]
> @GorgeousWang The tutorial is talking about how to create a **new** task in the cogdl. You can run examples in the `examples` directory of our repo.

thanks for your answer.
