### ISSUE TITLE
how to use cogdl in pycharm?

### ISSUE THREAD

**Issue by GorgeousWang** [THUDM/cogdl#131]

**Comment by THINK2TRY** [comment]
Hi @GorgeousWang 
Thanks for your attention. I guess what you mean is how to run through CogDL's API instead of command-line. You can run this example https://github.com/THUDM/cogdl/blob/master/examples/gcn.py in Pycharm. I think it will work. 
If you want to build a new model or dataset, you can refer to other examples in https://github.com/THUDM/cogdl/tree/master/examples. I hope it helps.

**Comment by GorgeousWang** [comment]
> Hi @GorgeousWang
> Thanks for your attention. I guess what you mean is how to run through CogDL's API instead of command-line. You can run this example https://github.com/THUDM/cogdl/blob/master/examples/gcn.py in Pycharm. I think it will work.
> If you want to build a new model or dataset, you can refer to other examples in https://github.com/THUDM/cogdl/tree/master/examples. I hope it helps.
thanks for you answer.But there are some problems in the first example, when i run this code, the python console return some wrong information like this.
***********************************************************************wrong infromation******************
D:\Anaconda3\envs\pytorch\python.exe D:/codespace/pyspace/autocogdl/turial/gcn_example.py
Using backend: pytorch
Traceback (most recent call last):
  File "D:/codespace/pyspace/autocogdl/turial/gcn_example.py", line 32, in <module>
    dataset = build_dataset(args)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\cogdl\datasets\__init__.py", line 70, in build_dataset
    return DATASET_REGISTRY[args.dataset]()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\cogdl\datasets\pyg.py", line 27, in __init__
    super(CoraDataset, self).__init__(path, dataset, transform=T.TargetIndegree())
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\datasets\planetoid.py", line 56, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\data\\Cora\\Cora\\processed\\data.pt'

**** ******************************************************************************************************
i think i can not download your dataset from your code.

**Comment by THINK2TRY** [comment]
It seems that the reason is that you cannot visit  https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).

**Comment by GorgeousWang** [comment]
> It seems that the reason is that you cannot visit https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).

it works. thanks for your help.

**Comment by GorgeousWang** [comment]
> > It seems that the reason is that you cannot visit https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).
> 
> it works. thanks for your help.

Excuse me, could you tell me the raw data site of the citation datasets(Cora/CiteSeer/Pubmed) ?

**Comment by GorgeousWang** [comment]
> It seems that the reason is that you cannot visit https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).
by the way, could you tell me the raw data site of the citation datasets(Cora/CiteSeer/Pubmed) ? - . -~

**Comment by GorgeousWang** [comment]
> It seems that the reason is that you cannot visit https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).

by the way, could you tell me the raw data site of the citation datasets(Cora/CiteSeer/Pubmed) ? - . -~

**Comment by GorgeousWang** [comment]
> It seems that the reason is that you cannot visit https://github.com/kimiyoung/planetoid/ in your python console. We will fix this bug soon. If you want to run GNN models in citation datasets(Cora/CiteSeer/PubMed) now , you can download them from https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/ and place them in the appropriate folder(cogdl/data).

the same problem happened in other examples, could you provide the other datasets like ppi and wiki ?

PPI | Wikipedia
-- | --




PPI | Wikipedia
-- | --

**Comment by THINK2TRY** [comment]
You can refer to the data processing code in  https://github.com/PetarV-/DGI/blob/master/utils/process.py to get to know the  raw format of Cora/Citeseer/PubMed.

PPI and Wikipedia are also placed in https://cloud.tsinghua.edu.cn/d/3f4477d9648a4e96a3c1/
