### ISSUE TITLE
Advice: provide a script to download all datasets for offline usage

### ISSUE THREAD

**Issue by wangzk** [THUDM/cogdl#15]
Currrently, CogDL downloads the missing datasets on the fly. However, some servers are installed in an environment isolated from the Internet. It is inconvenient to use CogDL in such environment.

A script to download all the needed datasets into a local directory will be very helpful. Users can then upload the local directory to the remote server only once.

Thanks for considering the advice.

**Comment by cenyk1230** [comment]
Hi @wangzk,

Thanks for your suggestions. Actually, you can run the code in the local machine to download the datasets and upload them to the server. We will provide a script for downloading datasets soon.

**Comment by cenyk1230** [comment]
Hi @wangzk,

I have added the download script in the script directory. 
For example, you can use `python scripts/download.py -dt ppi wikipedia` (split by space) for downloading ppi and wikipedia datasets.
