### ISSUE TITLE
运行experiment(task="node_classification", dataset="cora", model="gcn", hidden_size=32, max_epoch=200)时，提示缺少cogdl\\match.yml文件

### ISSUE THREAD

**Issue by Novahh0714** [THUDM/cogdl#165]
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* How did you try to install CogDL (wheel, source):
* Any other relevant information:

## Checklist

- [ ] I followed the [installation guide](https://github.com/thudm/cogdl#requirements-and-installation).
- [ ] I set up CUDA correctly.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by cenyk1230** [comment]
Hi @Novahh0714,

Thank you for your attention to CogDL. What OS do you use? (Windows, or others?) Please give more details about the environment.

**Comment by cenyk1230** [comment]
@Novahh0714 Sorry, I think I find the problem. The pip package doesn't contain the `match.yml` file. We will fix it soon. You can first download the file manually from [this link](https://github.com/THUDM/cogdl/blob/master/cogdl/match.yml) and put it under the cogdl directory.

**Comment by cenyk1230** [comment]
@Novahh0714 We have fixed the issue and released a new version v0.2.0.post1. Please re-install the cogdl or upgrade the cogdl through `pip install -U cogdl`. Many thanks for reporting this bug.
