### ISSUE TITLE
Embedding vectors

### ISSUE THREAD

**Issue by LiuChuang0059** [THUDM/cogdl#17]
Can I output  the embedding vectors (contex vectors) as a file ?

**Comment by baoxin1100** [comment]
Same question, how can I get the embedding vectors?

**Comment by cenyk1230** [comment]
Hi @LiuChuang0059, @baoxin1100,

Thank you for your attention. I have added the code for exporting embedding vectors. For the unsupervised node classification task, our code will save the embedding vectors to the directory specified by `save-dir` now.
