### ISSUE TITLE
Possible label leakage problem with the link prediction task

### ISSUE THREAD

**Issue by yangkcatiu** [THUDM/cogdl#18]
This happens for undirected networks like PPI. The link prediction task class 

https://github.com/THUDM/cogdl/blob/4ed7838018400377dae9da30017399f56585208f/cogdl/tasks/link_prediction.py#L116

reads the adjacency matrix directly without removing duplicates, this means the the edge list would have (x, y) and (y, x) at the same time for every edge. 

(x, y) and (y, x) are referring to the same edge, producing the same cosine similarity for x and y in  evaluation later. However, the training-test splitting process treats them as independent edges. As a result, a great portion of the generated test edges are also in the training set, just with a reversed order of two ends.

I have tried resolving this label leakage issue, and I can only get about 0.8 ROC-AUC on PPI instead of over 0.9 reported in your leader board.

**Comment by cenyk1230** [comment]
Hi @yangkcatiu,

Thank you for reporting this to us. We will fix this issue as soon as possible.
