### ISSUE TITLE
怎样获得模型输出而不是准确率？

### ISSUE THREAD

**Issue by hhr114** [THUDM/cogdl#183]
## ❓ Questions & Help

Hi,
CogDL是很好的工作包，请问怎样获得结点分类模型对每个结点的预测值？如用GAT在Cora上执行半监督结点分类，希望得到输出尺寸为（2708，7）的预测矩阵，而不是简单的测试精度。

**Comment by THINK2TRY** [comment]
Thanks for your attention to CogDL. In addition to directly adding one more inference step in the source code `node_classification.py`, you can also build dataset, model and task step by step to get the output. One example is shown as follows.

```
from cogdl.datasets import build_dataset
from cogdl.models import build_model
from cogdl.tasks import build_task
from cogdl.options import get_default_args


def main():
    task = "node_classification"
    model = "gcn"
    dataset = "cora"
    args = get_default_args(task=task, dataset=dataset, model=model, hidden_size=32)
    args.dataset = args.dataset[0]
    args.model = args.model[0]

    dataset = build_dataset(args)
    args.num_features = dataset.num_features
    args.num_classes = dataset.num_classes
    
    model = build_model(args)
    
    task = build_task(args, dataset=dataset, model=model)
    result = task.train()
    
    model.eval()
    # the shape of output is (2708, 7)
    output = model.predict(dataset.data)
    print(result)
    print(output.shape)

if __name__ == "__main__":
    main()
```

**Comment by hhr114** [comment]
非常感谢，十分有用！！

**Comment by Closeressi** [comment]
> Thanks for your attention to CogDL. In addition to directly adding one more inference step in the source code `node_classification.py`, you can also build dataset, model and task step by step to get the output. One example is shown as follows.
> 
> ```
> from cogdl.datasets import build_dataset
> from cogdl.models import build_model
> from cogdl.tasks import build_task
> from cogdl.options import get_default_args
> 
> 
> def main():
>     task = "node_classification"
>     model = "gcn"
>     dataset = "cora"
>     args = get_default_args(task=task, dataset=dataset, model=model, hidden_size=32)
>     args.dataset = args.dataset[0]
>     args.model = args.model[0]
> 
>     dataset = build_dataset(args)
>     args.num_features = dataset.num_features
>     args.num_classes = dataset.num_classes
>     
>     model = build_model(args)
>     
>     task = build_task(args, dataset=dataset, model=model)
>     result = task.train()
>     
>     model.eval()
>     # the shape of output is (2708, 7)
>     output = model.predict(dataset.data)
>     print(result)
>     print(output.shape)
> 
> if __name__ == "__main__":
>     main()
> ```

你好，现在cogdl.tasks好像改了，现在要得到同样结果和f1值具体怎么实现呢？
