### ISSUE TITLE
Issue about unsupervised_graph_classification

### ISSUE THREAD

**Issue by ayanesakura** [THUDM/cogdl#185]
## ❓ Questions & Help

Hi,I just installed cogdl and tried to run a demo,but I found  is seems that unsupervised_graph_classification model and dataset are missing,for example ,gin and infograph
So,maybe something is wrong with my code?
My code is :
`experiment(task="unsupervised_graph_classification", dataset="proteins", model="infograph")`

**Comment by THINK2TRY** [comment]
Hi @ayanesakura , thanks for your attention to CogDL. I have tried to run the code as you mentioned but cannot reproduce the problem. Could you provide more details about your problem and how you install CogDL?
