### ISSUE TITLE
Having trouble using youtube dataset to do unsupervised node classification

### ISSUE THREAD

**Issue by abcbdf** [THUDM/cogdl#19]
when use youtube dataset to do unsupervised node classification. It will throw error:
```
"...cogdl\cogdl\tasks\unsupervised_node_classification.py", line 54, in __init__
    self.num_nodes, self.num_classes = self.data.y.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by cenyk1230** [comment]
Hi @abcbdf,

Thank you for your attention on CogDL. The YouTube dataset is designed for multiplex link prediction and has no node label for unsupervised node classification. You can choose other datasets for unsupervised node classification.
