### ISSUE TITLE
入侵检测

### ISSUE THREAD

**Issue by czkn** [THUDM/cogdl#20]
我想应用于入侵检测，入侵检测中的网络数据集要怎么处理呢？
KDDCup '99': http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html
NSL-KDD: http://www.unb.ca/cic/datasets/nsl.html
UNSW-NB15: https://www.unsw.adfa.edu.au/australian-centre-for-cyber-security/cybersecurity/ADFA-NB15-Datasets/
IDS2017: https://www.unb.ca/cic/datasets/ids-2017.html

**Comment by cenyk1230** [comment]
Hi @czkn,

Thank you for your attention on the cogdl. I am not sure whether a network embedding method can be used to solve the network intrusion detector problem.
