### ISSUE TITLE
wrong negative sampling in LINE? and some other suggestions

### ISSUE THREAD

**Issue by jiank2** [THUDM/cogdl#21]
In LINE's code, there might be a minor error in negative sampling part (if I understand it correctly). 
https://github.com/THUDM/cogdl/blob/a69a969020b8aa41cfcd8ac54511984bc5b32d62/cogdl/models/emb/line.py#L133-L137

If index j for negative samples start at 1, then the number of negative sample should be self.negative-1. For example, if you set self.negative=5, 0 is not the negative sample (since it is skipped in the for loop) and 1,2,3,4 are negative samples drawn by alias algorithm. And I also checked original implementation by Jian Tang, the range of negative sampling is set as negative+1 (please see below).
https://github.com/tangjianpku/LINE/blob/d5f840941e0f4026090d1b1feeaf15da38e2b24b/linux/line.cpp#L332-L348

Some other suggestions:
1. It seems that cora, citeseer, pubmed are not supported in current version. I tried to run on these datasets, but error occurs saying that datasets are not supported. It would be better to provide documentation on how to run tasks on these datasets, or how to add new datasets (e.g., data formats, paths, naming conventions) by myself to run tasks
2. It would be better if there are more details on: stats of datasets (e.g., labeled or not), which datasets are supported for which tasks.
3. It would be better to provide some docstrings/comments in source code indicating the meaning of some variables (e.g., input, output).

**Comment by lykeven** [comment]
@jiank2 
Thanks for your attention and good suggestions for our repo. 
You are right about the negative sampling implementation in LINE code and we will update the number of negative samples just like the original implementation.
We will also added your valuable suggestions for dataset support and docs to our schedule.
