### ISSUE TITLE
怎么获取模型的acc、recall、F1或者分类报告？

### ISSUE THREAD

**Issue by huihuijiangqiang** [THUDM/cogdl#214]
非常感谢你们开发并开源cogdl，请问怎样获得结点分类模型分分类报告而不是只显示acc呢？

十分感谢！！

**Comment by THINK2TRY** [comment]
非常感谢关注CogDL！请问这边是只需要有监督节点分类的结果 还是 有监督/无监督 都需要呢？无监督这边的话CogDL里面目前已经保存了生成的embedding

**Comment by huihuijiangqiang** [comment]
非常感谢回复，您好，我这边，有监督/无监督都需要。

**Comment by THINK2TRY** [comment]
你好，对于有监督的情况，可以先训练保存模型，再得到结果，比如 gcn + cora:

1. `python scripts/train.py --task node_classification --model gcn --dataset cora --save_model <model_path>`
2. `python scripts/train.py --task node_classification --model gcn --dataset cora --checkpoint <model_path> --inference`
则模型的预测结果会被保存在 `gcn_cora.pred`, 可以通过 `torch.load`读取

对于无监督的情况，每次训练得到的embedding保存在./embedding下，可以通过`np.load`读取，然后您可以训练一个 linear classifier 然后根据个人需要得到分类结果

**Comment by huihuijiangqiang** [comment]
非常感谢

**Comment by Closeressi** [comment]
> 非常感谢

你好，想问下这个怎么具体实现呢？
