### ISSUE TITLE
Optimize Exception Message

### ISSUE THREAD

**Issue by Somefive** [THUDM/cogdl#219]
Loading CogDL will report `Ninja is required to load C++ extensions`, which could be traced back to https://github.com/THUDM/cogdl/blob/94b8bc9bf8215f63eb1f0471457ca831817a9bf3/cogdl/operators/sample.py#L14

Similarly, the following code also has the same problem.
https://github.com/THUDM/cogdl/blob/94b8bc9bf8215f63eb1f0471457ca831817a9bf3/cogdl/operators/spmm.py#L26

It might be better to add extra message to the `print(e)` to identify the "Ninja" message is thrown here. Since the first line will be reached as soon as cogdl is imported, it might confuse the users that do not use this module.

**Comment by cenyk1230** [comment]
Thanks for pointing it out. Please help check whether this commit fixes the issue.
