### ISSUE TITLE
python scripts/train.py --task unsupervised_node_classification --dataset wikipedia --model gcn gat deepwalk node2vec hope  netmf netsmf  prone

### ISSUE THREAD

**Issue by zyjcs** [THUDM/cogdl#22]
`python scripts/train.py --task unsupervised_node_classification --dataset wikipedia --model gcn gat deepwalk node2vec hope  netmf netsmf  prone`
我是运行的上面的命令
出现如下的错误。环境都安装好了  macOS +torch1.4.0  无cuda,在笔记本本地跑的。
`Traceback (most recent call last):
  File "scripts/train.py", line 75, in <module>
    results = [main(args) for args in variant_args_generator(args, variants)]
  File "scripts/train.py", line 75, in <listcomp>
    results = [main(args) for args in variant_args_generator(args, variants)]
  File "scripts/train.py", line 26, in main
    task = build_task(args)
  File "/Users/XXX/cogdl-master/cogdl/tasks/__init__.py", line 48, in build_task
    return TASK_REGISTRY[args.task](args)
  File "/Users/XXX/cogdl-master/cogdl/tasks/unsupervised_node_classification.py", line 56, in __init__
    self.model = build_model(args)
  File "/Users/XXX/cogdl-master/cogdl/models/__init__.py", line 108, in build_model
    return MODEL_REGISTRY[args.model].build_model_from_args(args)
  File "/Users/XXX/cogdl-master/cogdl/models/nn/gcn.py", line 71, in build_model_from_args
    return cls(args.num_features, args.hidden_size, args.num_classes, args.dropout)
  File "/Users/XXX/cogdl-master/cogdl/models/nn/gcn.py", line 76, in __init__
    self.gc1 = GraphConvolution(nfeat, nhid)
  File "/Users/zengyujian/cogdl-master/cogdl/models/nn/gcn.py", line 20, in __init__
    self.weight = Parameter(torch.FloatTensor(in_features, out_features))
TypeError: new() received an invalid combination of arguments - got (NoneType, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, int)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, int)`

**Comment by cenyk1230** [comment]
Hi @zyjcs,

Thank you for your attention. GCN and GAT models are used for the (semi-)supervised node classification task (`node_classification`) and are not supported for the unsupervised node classification task (`unsupervised_node_classification`). Therefore, you should remove `gcn` and `gat` from the command, i.e., `python scripts/train.py --task unsupervised_node_classification --dataset wikipedia --model deepwalk node2vec hope netmf netsmf prone`. We will try to catch these situations and give reminders when using unsuitable commands.
