### ISSUE TITLE
Split package requirements

### ISSUE THREAD

**Issue by Harry-Chen** [THUDM/cogdl#24]
Not all packages in `setup.py` of `cogdl` are actually needed for end-users, and `setuptools` supports split requirements into `install_requires`, `setup_requires` and `tests_requires`.

It will great to move packages like `pytest` and `spinx` out of `install_requires`, the former should be in `tests_requires`, and the latter should be removed because `doc` folder has its own `requirements.txt`.

**Comment by Harry-Chen** [comment]
FYI, only these are actually needed to use the code `cogdl`:

* `numpy`, `scipy`
* `torch`
* `tqdm`
* `six`
* `gensim`
* `pytorch-geometric`

Some others are uses in `scripts`, some to test / generate docs.

**Comment by Harry-Chen** [comment]
A good example: https://github.com/thu-ml/zhusuan/blob/master/setup.py

**Comment by cenyk1230** [comment]
Hi @Harry-Chen,

Thank you very much for your kind suggestions. We will update the requirements in the `setup.py` as soon as possible.
