### ISSUE TITLE
How to setup codgl in cluster!!

### ISSUE THREAD

**Issue by aj280192** [THUDM/cogdl#25]
Hi,
I am trying to setup cogdl in a virtual environment of a cluster. Can you provide setup instruction to do so!!
Thanks,
Ajay Madhavan

**Comment by cenyk1230** [comment]
Hi @aj280192,

Thank you for your attention. We only test our cogdl in a single machine with multiple GPUs and we haven't tested cogdl in a cluster yet. We are afraid that we cannot provide the setup instruction for a cluster.

**Comment by aj280192** [comment]
Hi,
Thank you for your reply. Can you provide me details to setup cogdl in local machine!!. I have installed the requirements, is there any pip command to install cogdl ?

**Comment by cenyk1230** [comment]
Hi @aj280192,

For a local machine, you can see the instructions here: https://github.com/THUDM/cogdl#requirements-and-installation. Before installing the cogdl, you should first install PyTorch and PyTorch Geometric.
