### ISSUE TITLE
请问GATNE-t 和 GATNE-i模型都实现了吗？

### ISSUE THREAD

**Issue by zhangjiekui** [THUDM/cogdl#253]
## ❓ Questions & Help
GATNE原论文中实现了GATNE-t 和 GATNE-i, 本库中是不是只实现了GATNE-t ？因为我看 GATNE数据集和模型中都没有用到features

**Comment by cenyk1230** [comment]
Hi @zhangjiekui，目前是只实现了GATNE-T模型。如果你需要用到GATNE-I的话，可以运行THUDM/GATNE那个仓库下的代码https://github.com/THUDM/GATNE/blob/master/src/main_pytorch.py。之后我们会尽快把GATNE-I加进来。

**Comment by zhangjiekui** [comment]
谢谢！
