### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal  on google colab

### ISSUE THREAD

**Issue by gayanku** [THUDM/cogdl#268]
## To Reproduce

On google colab 
1. !git clone https://github.com/THUDM/cogdl.git
%cd cogdl
!pip install -e .
1. !python scripts/parallel_train.py --task node_classification --dataset cora --model gcn gat --device-id 0 1 --seed 0 1

## Expected behavior

Should provide the model acc.

## Environment

 - CogDL version: cogdl-0.4.0
 - OS (e.g., Linux): "Linux 4eaee82282c2 5.4.104+ #1 SMP Sat Jun 5 09:50:34 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux"
 - Python version: Python 3.7.11
 - PyTorch version: 1.9.0+cu102
 - PyG version (if installed):
 - DGL version (if installed):
 - CUDA/cuDNN version (if applicable):
 - Any other relevant information:

## Additional context

[Error.txt](https://github.com/THUDM/cogdl/files/6951047/Error.txt)

**Comment by cenyk1230** [comment]
Hi @gayanku, how many GPUs do you have on Colab? The running script (`--device-id 0 1`) needs two GPUs for parallel training. If you only have one, please try to use `train.py`.

**Comment by gayanku** [comment]
Thank you.
