### ISSUE TITLE
[Question] Which node classification to use for which model?

### ISSUE THREAD

**Issue by aj280192** [THUDM/cogdl#28]
Hi,
Which one of the 4 node classification tasks should be used for the model 'deep walk', 'node2vec','NetMF', and 'NetSMF'?.

**Comment by cenyk1230** [comment]
Hi @aj280192,

These four methods belong to unsupervised network embedding. Thus, you should use `unsupervised_node_classification`.

**Comment by aj280192** [comment]
Hi @cenyk1230 ,

Can the graph clustering task be used for these models?...
