### ISSUE TITLE
关于无监督图分类中graph2vec的精度问题

### ISSUE THREAD

**Issue by ShenchenYu98** [THUDM/CogDL#284]
## ❓ Questions & Help

你好，我在运行 python scripts/train.py --task unsupervised_graph_classification --dataset 'collab' --model graph2vec --degree-feature时，训练结果acc只有0.66左右。我在tasks文件夹中的readme.md看到graph2vec方法应用到collab数据集时acc能有0.85，请问这中间0.2的差异是有什么参数是我没有设置到的吗，还是说是其他原因？还有就是我想请问一下degree-feature这个参数的意义是什么，我在相关的py文件中并没能找到相关的注释。我的问题可能表较多，因为我刚刚开始GNN相关的学习，希望您能百忙之中抽出时间解答一下，谢谢！

**Comment by ShenchenYu98** [comment]
感谢回答。还想请教一下，我现在在测试自己的数据集，在数据集的制作配套cogdl这个库时，请问节点属性（如度，中心性等）（node_attribute）这类数据是适配Graph这个类中的哪个参数呢？目前我用到了edge_index和edge_weight。我在data.py中没能找到节点属性这类的参数。

**Comment by cenyk1230** [comment]
节点属性是Graph中的x这个属性
