### ISSUE TITLE
metapath2vec --schema

### ISSUE THREAD

**Issue by rain0831** [THUDM/cogdl#29]
Hi, 
When I choose schema "0-1-0,0-1-2-1-0”, not all nodes are included in walks.
It will throw error:
`KeyError: "word '6931' not in vocabulary"`
How to solve this problem?Thanks!

**Comment by lykeven** [comment]
Hi @rain0831,
In task `multiplex_node_classification`, we can run  `metapath2vec` algorithm on  GTN datasets like gtn-acm, which have 3 different type nodes(0, 1, 2) and four different edges(0-1, 1-0, 0-2, 2-0). Thus there are no edges like '1-2' or '2-1' and the nodes who are type 2 are not included in walks.

I recommend you to use schema ''0-1-0,0-2-0,1-0-2-0-1", it will works fine.
