### ISSUE TITLE
documents

### ISSUE THREAD

**Issue by Ashappyboy** [THUDM/cogdl#31]
@neozhangthe1 
Hi, I'm very curious about your project. I would like to consult with your the problem what is the difference from the geometrics. 
And I found that the documents are incomplete and lace some introduction about how to use. And I expect the update the documents.
thank you!

**Comment by cenyk1230** [comment]
Hi @Ashappyboy,

Thank you for your attention to cogdl. You can easily use our code to run all kinds of tasks defined by cogdl using the command line. The document is still incomplete and we are trying to write more details on it. You can check the basic usage from the README (https://github.com/thudm/cogdl#usage).
