### ISSUE TITLE
何时添加对Jittor的支持

### ISSUE THREAD

**Issue by sleeplessai** [THUDM/cogdl#319]
## 🚀 Feature
请添加对Jittor backend的支持。

**Comment by cenyk1230** [comment]
Hi @sleeplessai,

感谢对cogdl的关注！我们正在考虑支持更多的后端（例如Jittor），但是这目前不是我们优先级最高的事项。预计得等到过完年之后会重点推进这一块的工作。抱歉，还请先用PyTorch后端。
