### ISSUE TITLE
关于GIN整图分类的数据集划分

### ISSUE THREAD

**Issue by kou18n** [THUDM/cogdl#333]
## ❓ Questions & Help
想请教一下，论文里面写的是监督学习的整图分类用了10折交叉验证重复10次分割90%-10%，我在源码里面没有找到。
默认参数下，下面代码的结果是交叉验证的结果还是0.5train,0.2val,0.3test结果，谢谢。
``
experiment(model=["gin"], dataset=dataset)
``

**Comment by cenyk1230** [comment]
Hi @kou18n ,

感谢对cogdl的关注！
v0.5版本开始用的是单次随机划分（通过train_ratio/test_ratio来控制比例）。你列的那个代码的结果是0.5/0.2/0.3划分的结果。在v0.4及更老的版本中，我们用的是交叉验证。

**Comment by kou18n** [comment]
@cenyk1230 谢谢，清楚了。
