### ISSUE TITLE
unsupervised_node_classification evaluation

### ISSUE THREAD

**Issue by rain0831** [THUDM/cogdl#34]
Hi. When evaluating the performance of node classification, why LINE, NetMF, ProNE has the same result every time? For example, if use Wikipedia dataset on NetMF, It's always going to be this,
`| ('wikipedia', 'netmf') | 0.4373±0.0000  | 0.4747±0.0000  | 0.4883±0.0000  | 0.4953±0.0000  | 0.5022±0.0000  |`

Looking forward to your reply, Thanks!

**Comment by cenyk1230** [comment]
Hi @rain0831,

Thank you for your attention to the CogDL. Could you please report your running command? I wonder whether you set several different seeds. I just ran `python scripts/train.py --task unsupervised_node_classification --dataset wikipedia --model line netmf --seed 0 1 2 3 4` and got the following results:
| Variant                | Micro-F1 0.1   | Micro-F1 0.3   | Micro-F1 0.5   | Micro-F1 0.7   | Micro-F1 0.9   |
|------------------------|----------------|----------------|----------------|----------------|----------------|
| ('wikipedia', 'line')  | 0.4961±0.0039  | 0.5193±0.0007  | 0.5290±0.0019  | 0.5350±0.0013  | 0.5414±0.0066  |
| ('wikipedia', 'netmf') | 0.4541±0.0022  | 0.4929±0.0022  | 0.5042±0.0016  | 0.5083±0.0060  | 0.5125±0.0032  |
