### ISSUE TITLE
cogdl 0.5.2如何像0.4版本一样在命令行中指定任务？

### ISSUE THREAD

**Issue by Hdligence** [THUDM/cogdl#343]
## ❓ Questions & Help

现在的版本在命令行输入运行命令，最终输出的结果只有acc。怎样能够像0.4.1版本指定任务（如节点分类）去跑代码，得到相应任务的评价输出结果

**Comment by cenyk1230** [comment]
Hi @Hdligence,
现在不需要指定task，可以直接运行。cogdl会自动根据dataset和model来自动选择相应的训练任务。
