### ISSUE TITLE
一些数据集下载不了

### ISSUE THREAD

**Issue by wszhs** [THUDM/cogdl#345]
## ❓ Questions & Help

你好，有三个问题需要解答一下
1 一些数据集不知道是不是权限的问题，下载下来无法使用
比如 amazon-s  yelp等数据集，能将adj_full.npz等下载下来，但是下载下来的其实是报错的网页源码而不是真正的数据，希望得到解决
2 一些新数据集比如alpha，yelpchi能否增加数据集说明，比如alpha这个是区块链数据集吗，由于没有数据集说明不是特别清楚
3 评估指标只有acc对有些数据集说明不是很充分，比如yelpchi，正负类不是很平衡，用cogdl跑出来的acc结果是0.85，但是其实recall只有0，几乎没有效果，那么是这个数据集本身的问题吗？
希望得到解答，非常感谢
中科院信工所学生

**Comment by cenyk1230** [comment]
Hi @wszhs,

感谢关注cogdl。我们正在更新这些数据集的下载链接（#346）。
一些新数据集我们还在整理中，你可以先从这两个数据集的来源中查看具体说明：
- alpha：http://www.meng-jiang.com/pubs/gal-cikm20/gal-cikm20-paper.pdf
- yelpchi：https://arxiv.org/pdf/2104.01404.pdf

**Comment by wszhs** [comment]
嗯呢，非常感谢，持续关注中，cogdl的源码不难读，加快了我的离散数据的对抗攻击的研究

**Comment by cenyk1230** [comment]
可以试一下master分支的代码

**Comment by wszhs** [comment]
> 可以试一下master分支的代码

看的和跑的代码都是master分支的

**Comment by cenyk1230** [comment]
你重新pull一下试试吧 master上已经更新了 修复了失效的链接。

**Comment by wszhs** [comment]
> 你重新pull一下试试吧 master上已经更新了 修复了失效的链接。

可以了可以了，非常感谢！
