### ISSUE TITLE
由于gensim更新，调用gensim word2vec API时出错

### ISSUE THREAD

**Issue by Saltsmart** [THUDM/cogdl#360]
https://github.com/THUDM/cogdl/blob/438f5a9fecc1ae727394b135d2b94714cf35d776/cogdl/models/emb/deepwalk.py#L60-L68

参照[gensim](https://radimrehurek.com/gensim/models/word2vec.html?highlight=word2vec#module-gensim.models.word2vec)的API reference，4.2.0版本gensim.models.word2vec已经不使用 `size`（应为 `vector_size` ）和 `iter` （应为 `epochs` ）。

**Comment by cenyk1230** [comment]
感谢指出这个问题。我们暂时限制了gensim的版本为<4.0。
