### ISSUE TITLE
How to run the unsupervised graphsage by using command?

### ISSUE THREAD

**Issue by Peterecoding** [THUDM/cogdl#37]
It seems cannot use the command "--task unsupervised_node_classification --dataset cora --model graphsage --seed 0 1 2 3 4" to run the unsupervised graphsage

**Comment by THINK2TRY** [comment]
Hi @Peterecoding,
Thank you for your attention to the CogDL. In Cogdl we add unsupervised graphsage as `unsup_graphsage`. You can use `python scripts/train.py --task unsupervised_node_classification --model unsup_graphsage --dataset cora`  to run the unsupervised graphsage.

**Comment by Peterecoding** [comment]
Thank you for your reply. The project can work by using your provided command.
