### ISSUE TITLE
One problem while using the RevGNNLayer from the cogdl.layers

### ISSUE THREAD

**Issue by bin123apple** [THUDM/cogdl#411]
_##_ ❓ Questions & Help
Hey! I am trying to create a 1000 layers GCN model for node classification task. But I don't have enough memory to support a 1000 layers model. So I am trying to use the **_RevGNNLayer_** from the **_cogdl.layers_** to reduce the memory consumption. I meet some problems while using that, Could you help me to solve it? Thanks for the help!
Here is my model:
```
class GNN_mult_deep(torch.nn.Module):
    def __init__(self, input_size, hidden_size, num_classes,hidden_layers):
        super(GNN_mult_deep, self).__init__()
        self.input_fc = nn.Linear(input_size, hidden_size)
        self.output_fc = nn.Linear(hidden_size, num_classes)
        
        self.gcn_layers = nn.ModuleList()
        for i in range(hidden_layers):
            gcn_layer = GCNLayer(hidden_size, hidden_size)
            # 得到Pre-activation的残差连接GCN层
            resgcn_layer = ResGNNLayer(gcn_layer,hidden_size)
            # 得到Reversible的GCN层
            revgcn_layer = RevGNNLayer(resgcn_layer ,1)
            self.gcn_layers.append(revgcn_layer)

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr
     
        x = self.input_fc(x)
        
        for gcn_layer in self.gcn_layers:
            x = gcn_layer(data,x)
            
        x = self.output_fc(x)
        return x
```

And for this line:
`def forward(self, data):`
The **_data_** is from torch_geometric.data

And the bug happens in this line:
`x = gcn_layer(data,x)`

The bug shows: **'GlobalStorage' object has no attribute 'requires_grad'**

Could you help me to check what is wrong with my usage or my model? Thanks!

**Comment by cenyk1230** [comment]
Hi @bin123apple,

Please check the forward function of `GCNLayer` from https://github.com/THUDM/cogdl/blob/master/cogdl/layers/gcn_layer.py. The input of the forward function should be `cogdl.data.Graph` and `torch.Tensor`.

**Comment by bin123apple** [comment]
Thanks for the reply！I just changed my _**data**_ from  torch_geometric.data to cogdl.data.Graph and my **_x_** is a torch.tensor.
Here is my **_data_**:
`from cogdl.data import Graph`
```
# data = Data(x = featrues, edge_index = edge_index_train ,train_mask = train_mask,test_mask = train_mask, y = lables) 
    data = Graph(x=featrues, edge_index=edge_index_train, y=lables, train_mask=train_mask, val_mask=train_mask, test_mask=train_mask)
```
But  the bug shows: 'Graph' object has no attribute 'requires_grad'
Could you help me to check what is the reason？ I think there might be some tiny problems inside the **_RevGNNLayer_** model？ Thanks a lot！

**Comment by cenyk1230** [comment]
Please check the usage of RevGCN (https://github.com/THUDM/cogdl/blob/master/cogdl/models/nn/revgcn.py). From line 84, maybe you should first set `graph.requires_grad= False` to avoid the error.

**Comment by bin123apple** [comment]
Thank for the ready-to-use model information, my code is good now,  it is very useful！
