### ISSUE TITLE
pip 安装 cogdl失败

### ISSUE THREAD

**Issue by BearBiscuit05** [THUDM/cogdl#416]
## Environment

* OS:Ubuntu20.04
* Python version:3.10
* PyTorch version:1.12.0
* CUDA/cuDNN version:11.3./8.0
* How did you try to install CogDL (wheel, source):wheel
* Any other relevant information:

## Checklist

- [ √] I followed the [installation guide](https://github.com/thudm/cogdl#requirements-and-installation).
- [√ ] I set up CUDA correctly.
- [ ×] I do have multiple CUDA versions on my machine.

## Additional context
报错信息如下：
```
 Building wheel for gensim (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1251 lines of output]
.....
.....
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gensim

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure
```

**Comment by alan890104** [comment]
我用python 3.8 安裝就能成功，python3.10在安裝gensim時會失敗~

**Comment by BearBiscuit05** [comment]
> 我用python 3.8 安裝就能成功，python3.10在安裝gensim時會失敗~

是的，python3.10版本会产生这个报错。问题已解决，感谢。
