### ISSUE TITLE
有关内部函数的实现

### ISSUE THREAD

**Issue by Sangs3112** [THUDM/CogDL#434]
## ❓ Questions & Help

1. 请问cogdl.utils中的edge_softmax具体是实现了一个什么样的操作呢
2. HGB论文中的数据集原本在清华云盘中，但现在无法下载了。
3. 能否用别的方式实现一个简单但是有效的MultiHeadSpMM,因为我的工作涉及超图，但是在cogdl上无法进行超图方面的计算

**Comment by cenyk1230** [comment]
Hi @Sangs3112 
1. 用于GAT模型中每个节点对邻居节点聚合权重的归一化
2. HGB的数据集你看能否从HGB的github页面里下载（https://github.com/THUDM/HGB#heterogeneous-graph-benchmark）
3. 关于超图GNN，可以看下这个工作能否帮到你（https://github.com/fishmingyu/HyperGef）
