### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dim'

### ISSUE THREAD

**Issue by luoda888** [THUDM/cogdl#5]
python train.py --task node_classification --dataset wikipedia --model gcn

AttributeError: 'NoneType' object has no attribute 'dim'

**Comment by qibinc** [comment]
Hi @luoda888 ,

Thanks for using this toolkit. The wikipedia dataset doesn't have node attributes and the current GCN implementation is for node classification with attributes.

**Comment by luoda888** [comment]
Training the CORA dataset will report the same error

**Comment by luoda888** [comment]
> Hi @luoda888 ,
> 
> Thanks for using this toolkit. The included wikipedia dataset doesn't have node attributes (only edges and edge weights) and the current GCN implementation is for node classification with attributes.
> 
> See http://keg.cs.tsinghua.edu.cn/cogdl/node-classification.html and http://keg.cs.tsinghua.edu.cn/cogdl/datasets.html
> 
> If you want to try out GCN on some dataset, please specify dataset from one of (cora, citeseer, pubmed). For example:
> 
> ```
> python train.py --task node_classification --dataset cora --model gcn
> ```
> 
> If you want to try some model on Wikipedia, please specify task to unsupervised_node_classification and specify model from one of (prone, deepwalk, node2vec, hope, grarep, netmf, netsm). For example:
> 
> ```
> python train.py --task unsupervised_node_classification --dataset cora --model gcn
> ```
> 
> Thanks!
