### ISSUE TITLE
how to run unsupervised_node_classification task on graphsage model

### ISSUE THREAD

**Issue by liminxian** [THUDM/cogdl#6]
Dear author, when I tried run **unsupervised_node_classification task** on graphsage model, this error is shown as follow:

Traceback (most recent call last):
  File "train.py", line 76, in <module>
    results = pool.map(main, variant_args_generator())
  File "/home/mli/.localpython/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/mli/.localpython/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: new() received an invalid combination of arguments - got (NoneType, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, int)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, int)

**Comment by liminxian** [comment]
here is my script:
python3 train.py --task unsupervised_node_classification  --dataset cora  --model graphsage

**Comment by qibinc** [comment]
Hi @liminxian ,

Thanks for using this toolkit. However, I'm sorry to say that currently we don't support GraphSAGE on unsupervised_node_classification.

The unsupervised_node_classification is meant to test graph embedding algorithms. Datasets for this tasks include Blogcatalog, Wikipedia, etc, which don't contain *node attributes*. But yeah you're right, unsupervised representation learning on Cora, Citeseer with methods like GraphSAGE should be available.

I apologize for the inconvenience caused. We current don't support this but it's definitely on our schedule. We would appreciated it very much if you would like to help implement it :)

Best, 
Qibin

**Comment by liminxian** [comment]
Hi, qibin, thanks for the reply. 
I have a further question: If I want to run the **unsupervised** GraphSAGE training code, what kind of setting I should make? Is the unsupervised_node_classification task necessary or other task is also fine? Thanks.

**Comment by qibinc** [comment]
Hi @liminxian ,

To the best of my knowledge, GraphSAGE requires nodes to have attributes. The corresponding dataset in this toolkit is Cora, Citeseer and Pubmed. The current available task on these datasets is node_classification, which is, however, trained in a supervised way. I suggest you make this new setting by modifying the `node_classification` setting, not from the `unsupervised_node_classification` because `node_classification` shares the same category of datasets and methods as unsupervised GraphSAGE.

Hope this helps.

**Comment by liminxian** [comment]
@qibinc Thanks for your suggestion. One more question: have you implement the unsupervised learning loss function (Eq.1 in GraphSAGE paper) in your code? If so, where is it?

**Comment by qibinc** [comment]
@aviczhl2
