### ISSUE TITLE
Running on new dataset

### ISSUE THREAD

**Issue by dusk039** [THUDM/cogdl#7]
Hi, 
I am wondering if this is limited to the datasets you have made available. Is there any documentation for how to format a new graph dataset to test? 

I apologize as this is likely not a code base issue, but the slack invite link is broken. 

Thanks,
Kayla

**Comment by qibinc** [comment]
Hi @dusk039 ,

I apologize that we don't have documentation on adding a new dataset yet. If your dataset has the format of matlab mat, have a look at [matlab_matrix.py](https://github.com/THUDM/cogdl/blob/master/cogdl/datasets/matlab_matrix.py). If your dataset has the format of edgelist, have a look at [edgelist_label.py](https://github.com/THUDM/cogdl/blob/master/cogdl/datasets/edgelist_label.py). You can inherit either the `MatlabMatrix ` or `EdgelistLabel` class and adding a dataset should be very easy like:

https://github.com/THUDM/cogdl/blob/0a354eaaaf851e7218197508e7e85a81d3fb5753/cogdl/datasets/matlab_matrix.py#L95-L101

**Comment by dusk039** [comment]
Thanks! That is very helpful, I will give it a try.
