### ISSUE TITLE
random.seed

### ISSUE THREAD

**Issue by Cloudcatcher888** [THUDM/cogdl#8]
I want to use the function _display_data.py_, I get the error:
```
Traceback (most recent call last):
  File "display_data.py", line 75, in <module>
    random.seed(args.seed)
  File "/Users/wangzhikai/.conda/envs/cogdl/lib/python3.7/random.py", line 126, in seed
    super().seed(a)
TypeError: unhashable type: 'list'
```

**Comment by cenyk1230** [comment]
Hi @Cloudcatcher888 ,

Thanks for using our cogdl and pointing this out. For _display_data.py_, it only supports passing one integer to the _seed_. It seems that the value of _seed_ is a list (default: [1]), which causes this error. We will deal with the inconsistent bug of the code immediately. Please accept my apologies for this mistake.
