### ISSUE TITLE
Some question about link prediction 

### ISSUE THREAD

**Issue by morningsky** [THUDM/cogdl#82]
It seems that it is complex to implement other link prediction model based cogdl due to the design of HomoLinkPrediction task, such as https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py.  Can you give me some ideas? Thanks.

**Comment by cenyk1230** [comment]
Hi @morningsky,

Thank you for your interest in CogDL. Do you mean that you want to use GNN models for link prediction?

**Comment by morningsky** [comment]
@cenyk1230  yes，if I want to utilize the  'build task' function for link prediction，it seems I must write a train function which can return embedding in my model, but the training process is wrapped in 'HomoLinkPrediction' class. Can you give an example of link prediction task by GCN 、GAT or SAGE.

**Comment by THINK2TRY** [comment]
@morningsky 
Thanks for you interest. To implement 'link prediction' task as you expect, the models in CogDL need to be slightly modified to meet your need. It takes some time but we will do it and  provide an example as soon as possible.

**Comment by morningsky** [comment]
@THINK2TRY  well o(￣▽￣)ｄ
