### ISSUE TITLE
Problem with testing graph classification models

### ISSUE THREAD

**Issue by Sahandfer** [THUDM/cogdl#83]
Hello, 
I have been trying out different graph classification models on the available datasets. Running some models on a number of datasets for this task generates 'RuntimeError: There were no tensor arguments to this function' in the beginning or middle of the training phase. In addition, I haven't been able to observe the accuracy that is provided in the README file from training the given models. So I'm wondering what the problem could be, whether it is a bug or a dependancy problem, since I'm also trying to get the results for my newly added graph classification model. Thank you

**Comment by THINK2TRY** [comment]
@Sahandfer 
Thank you for your interest. Could you please provide more details about your problem? Did you run graph classification model in MUTAG dataset? If so, `batch_size` should be set to a appropriate small value becase MUTAG is too small. To reproduce the results in the table in README, `--kfold` should be added in the command to run a 10-fold cross-validation. I hope that helps.

**Comment by Sahandfer** [comment]
Yes, decreasing the batch_size fixed the problem. Thank you
