### ISSUE TITLE
Some Advice

### ISSUE THREAD

**Issue by wenruij** [THUDM/cogdl#9]
### 1.Adding docs for preparing data
Like what Euler does: [Preparing-Data](https://github.com/alibaba/euler/wiki/Preparing-Data)

### 3.Description for Graph Structure
- supporting bipartite graph? 
- supervised or unsupervised?

**Comment by qibinc** [comment]
Dear @wenruij ,

Thank you for your valuable suggestions. We have added them to our schedule.

**Comment by wenruij** [comment]
Sounds great, full of expectation.
