### ISSUE TITLE
Where is the DBLP dataset (51,264 nodes)?

### ISSUE THREAD

**Issue by scottshufe** [THUDM/cogdl#97]
Hi, does anyone know where the DBLP dataset with 51264 nodes and 127,968 edges is? (mentioned in this page: https://keg.cs.tsinghua.edu.cn/cogdl/datasets.html)

**Comment by THINK2TRY** [comment]
Hi @scottshufe 
Thanks for your attention. The `DBLP` you mentioned was removed before. Sorry not to update docs in time. But you can still find the raw data in https://github.com/THUDM/ProNE/tree/master/data.

**Comment by scottshufe** [comment]
> Hi @scottshufe
> Thanks for your attention. The `DBLP` you mentioned was removed before. Sorry not to update docs in time. But you can still find the raw data in https://github.com/THUDM/ProNE/tree/master/data.

Thanks for your reply!
